---
title: "R Notebook"
output: html_notebook
---
## Pitprops 

```{r}
library(elasticnet)
data("pitprops")

## Table 1
PCA <- prcomp(pitprops, center = FALSE)
PCA$rotation[,1:6]
(PCA$sdev/sum(PCA$sdev)*100)[1:6]
cumsum(PCA$sdev/sum(PCA$sdev)*100)[1:6]
## Table 3
SPCA<-spca(pitprops, K = 6, type = "Gram", sparse = "penalty",
           trace = TRUE, para = c (0.06, 0.16, 0.1, 0.5, 0.5, 0.5))
SPCA
SPCA$loadings
SPCA$pev

source("GAS.R")

lfit <- gas.pca(pitprops,type='Gram',n=13,d=6,
                adaptive=T,method='GAS')


pit_pc<-cbind(PCA$rotation[,1:6],SPCA$loadings[,1:6])



## Figure 2
# lambda.grid <- seq(0, 3.5, 0.01)
# PEVmatrix <- matrix(0, ncol = 6, nrow = length(lambda.grid))
# for (i in lambda.grid)
# {
# cat(i,"\n")
# SPCA<-spca(pitprops, K = 1, type = "Gram", sparse = "penalty", lambda = 0,
#            para = rep(i,6), eps.conv = 1e-4)
# PEVmatrix[i, ] <- SPCA$pev
# }
# 
# plot(lambda.grid, PEVmatrix[,1], type = "l", xlim = c(0, 0.2))


```

## Teaching data

```{r}
teaching_df<-read.table(file.choose(), header = FALSE, sep = "", dec = ".")
colnames(teaching_df)<-paste("Q",1:9)

PCA_teaching <- prcomp(teaching_df, center = FALSE)

cumsum(PCA_teaching$sdev/sum(PCA_teaching$sdev)*100)

SPCA_teaching<-gas.pca(teaching_df,type='predictor',n=251,d=3,
                       adaptive=F,method='SPCA')
GAS_teaching<-gas.pca(teaching_df,type='predictor',n=251,d=3,
                       adaptive=T,method='GAS')

stargazer(GAS_teaching$loadings)

df<-cbind(PCA_teaching$rotation[, 1:3],SPCA_teaching$loadings[,1:3],GAS_teaching$loadings[,1:3])
library(stargazer)
stargazer(df)
```

## Big Five Data

```{r}
library(qgraph)

big5_df<-big5

PCA_big5 <- prcomp(big5_df, center = TRUE,scale= TRUE)

cumsum(PCA_big5$sdev/sum(PCA_big5$sdev)*100)[1:5]

SPCA_big5<-gas.pca(big5_df,type='predictor',n=500,d=5,
                       adaptive=F,method='SPCA')
GAS_big5<-gas.pca(big5_df,type='predictor',n=500,d=5,
                       adaptive=T,method='GAS')


df<-cbind(PCA_big5$rotation[, 1:3],SPCA_big5$loadings[,1:3],GAS_big5$loadings[,1:3])

```



